import { Inter } from 'next/font/google'
import '../styles/globals.css'
import { NoteProvider } from '@/Provider/Provider'
import { Layout } from '@/components/Layout/Layout'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NoteProvider>
          <Layout>
            {children}
          </Layout>
        </NoteProvider>
      </body>
    </html>
  )
}
